Update .env file to hide more sensitive information.
jasonnoble/pivotal-tracker pull request #36
Opened 2017-02-02 23:19 UTC by wlffann

Add new variables to .env file to remove personal information from .yml files.

[#138940073]

2017-02-02 23:37 UTC, jasonnoble commented
Please add to Contributing.md to explain how to find these new values.

2017-02-03 00:32 UTC, wlffann commented
@jasonnoble I updated the Contributing.md file but I can't find the `PIVOTAL_MEMBERSHIP_ID` anywhere on Pivotal Tracker without making a request to the API. Since this was the variable that was giving trouble earlier, maybe it shouldn't be included in the .env file?

2017-02-03 16:50 UTC, jasonnoble requested changes

2017-02-03 16:50 UTC, jasonnoble commented on spec/spec_helper.rb
> +    ENV['PIOVTAL_MEMBERSHIP_ID'].to_i
Spelling...

2017-02-03 16:50 UTC, jasonnoble commented on .env.example
> +FULL_NAME='YOUR_FULL_NAME'
Let's alphabetize these?

2017-02-03 16:56 UTC, wlffann commented on .env.example
> +FULL_NAME='YOUR_FULL_NAME'
Good idea! I'm on it.

2017-02-03 16:56 UTC, wlffann commented on spec/spec_helper.rb
> +    ENV['PIOVTAL_MEMBERSHIP_ID'].to_i
Thanks!

2017-02-03 18:15 UTC, lucyconklin commented on spec/lib/pivotal-tracker/account_spec.rb
>        new_membership = (account.memberships.create(membership_params))
This might be a good place for another factory once we get that branch merged in.

2022-03-07 17:45 UTC, closed without merging