Add Account#memberships method
jasonnoble/pivotal-tracker pull request #5
Opened 2017-01-31 01:51 UTC by tmikeschu

Worked with @kheppenstall and @damwhit

Add Account.find(account_id) and Account#memberships methods for related
API endpoints. All tests pass.

[#138675877]

2017-01-31 16:21 UTC, jasonnoble requested changes

2017-01-31 16:21 UTC, jasonnoble commented on lib/pivotal-tracker/account.rb
> +class PivotalTracker::Account
```
module PivotalTracker
  class Account
```

2017-01-31 16:21 UTC, jasonnoble commented on lib/pivotal-tracker/account.rb
> +      puts response.inspect
We should probably analyze the error message a bit...  It'd be cool to see "Only Admins and Owners can see memberships" or something along those lines.

2017-01-31 16:21 UTC, jasonnoble commented on lib/pivotal-tracker/account_membership.rb
> +  def initialize(membership_attributes)
Do we need to set the values?  Similar to https://github.com/jasonnoble/pivotal-tracker/pull/5/files#diff-7d3104964801ebf75a831f703baa07a0R7 or is that another story?

2017-01-31 16:21 UTC, jasonnoble commented on lib/pivotal_tracker.rb
> +require 'pivotal-tracker/account'
Should we use autoload here?  http://www.rubyinside.com/ruby-techniques-revealed-autoload-1652.html

2017-01-31 16:21 UTC, jasonnoble commented on spec/lib/pivotal-tracker/account_spec.rb
> +      let(:account_id) { 962753 }
Should this be a `ENV` value?

2017-01-31 16:21 UTC, jasonnoble commented on spec/lib/pivotal-tracker/account_spec.rb
> +        expect(membership).to be_a(PivotalTracker::AccountMembership)
👍

2017-01-31 18:48 UTC, tmikeschu commented on lib/pivotal-tracker/account.rb
> +class PivotalTracker::Account
@jasonnoble if we want to change this convention, we need a story for the other models as well. Also, it would still be a PivotalTracker _class_, right?

```
class PivotalTracker
  class Account
```

2017-01-31 18:48 UTC, tmikeschu commented on lib/pivotal-tracker/account_membership.rb
> +  def initialize(membership_attributes)
@jasonnoble Since we have the functionality in the story working, we decided to leave this for another story.

2017-01-31 18:48 UTC, tmikeschu commented on lib/pivotal_tracker.rb
> +require 'pivotal-tracker/account'
@jasonnoble 👍

2017-01-31 18:48 UTC, tmikeschu commented on spec/lib/pivotal-tracker/account_spec.rb
> +      let(:account_id) { 962753 }
@jasonnoble 👍

2017-01-31 19:52 UTC, tmikeschu commented on lib/pivotal-tracker/account.rb
> +      puts response.inspect
👍

2017-01-31 20:37 UTC, jasonnoble commented on lib/pivotal-tracker/account_membership.rb
> +  def initialize(membership_attributes)
Did you write up that new story?

2017-01-31 20:49 UTC, jasonnoble requested changes

2017-01-31 20:49 UTC, jasonnoble commented on lib/pivotal-tracker/account.rb
> +class PivotalTracker
`module PivotalTracker`

2017-01-31 20:49 UTC, jasonnoble commented on lib/pivotal-tracker/account.rb
> +        puts "Only Admins and Owners can see account memberships"
raise(PivotalTracker::PermissionDenied, "Only Admins and Owners can see account memberships")

2017-01-31 20:49 UTC, jasonnoble commented on lib/pivotal-tracker/account.rb
> +        puts "Only Admins and Owners can see account memberships"
In `lib/pivotal_tracker.rb`:

```
class PivotalTracker
  PermissionDenied = Class.new(Error)
end
```

2017-01-31 21:03 UTC, tmikeschu commented on lib/pivotal-tracker/account_membership.rb
> +  def initialize(membership_attributes)
Done

2017-01-31 21:07 UTC, tmikeschu commented on lib/pivotal-tracker/account.rb
> +        puts "Only Admins and Owners can see account memberships"
👍

2017-01-31 21:25 UTC, tmikeschu commented on lib/pivotal-tracker/account.rb
> +class PivotalTracker
Addressed. Thanks for talking through this with me.

2017-02-01 20:31 UTC, jasonnoble commented on lib/pivotal-tracker/account.rb
> +class PivotalTracker::Account
We decided to go with `class PivotalTracker::Account` because `PivotalTracker` is a class, so it can't be a module.

2017-02-01 20:32 UTC, merged